version: '3'

services:
  churninsight:
    build: churninsight
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: churninsight
      POSTGRES_USER: ${DS_USNAME}
      POSTGRES_PASSWORD: ${DB_PS}
    ports:
      - "5432:5432"