name: Ping Render App

on:
  schedule:
    - cron: "*/10 * * * *"   # cada 10 minutos
  workflow_dispatch:         # permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping health endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://churn-api-v2-0.onrender.com/health
          
      - name: Ping swagger endpoint back
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://backend-churninsight-app-1.onrender.com/swagger-ui/index.html
